const GET_CONFIG = 'GET_CONFIG';
const SET_LABEL_FOCUS = 'SET_LABEL_FOCUS';
const SET_FORM_LOGIN = 'SET_FORM_LOGIN';
const SET_FORM_REGISTER = 'SET_FORM_REGISTER';

export default {
    GET_CONFIG,
    SET_LABEL_FOCUS,
    SET_FORM_LOGIN,
    SET_FORM_REGISTER,
};
